### ISSUE TITLE
Support Configuration Overrides for the experimental cli.

### ISSUE THREAD

**Issue by Standard8** [prettier/prettier-cli#70]
I've been trying out the new experimental CLI, and it is indeed seeming to be a lot faster.

Something I've noticed is that it appears there's no current support for Configuration Overrides. I suspect it just hasn't been added yet, which is fine, but as I couldn't see an existing issue for it, I thought I'd file one for helping with tracking.

STR

1. Set up a repo with a `.prettierrc.js` such as the one below:

```js
module.exports = {
  arrowParens: "avoid",
  endOfLine: "lf",
  printWidth: 80,
  tabWidth: 2,
  trailingComma: "es5",
  overrides: [
    {
      files: "*.css",
      options: {
        parser: "css",
        // Using a larger printWidth to avoid wrapping selectors.
        printWidth: 160,
      },
    },
  ],
};
```

2. Run the formatter

Expected Results

The CSS files are formatted correctly, with line width 160.

Actual Results

The CSS files are formatted with line width 80.

**Comment by fisker** [comment]
@43081j I thought this was fixed?

**Comment by fabiospampinato** [comment]
@fisker I think we have a TODO left about prefixing globs with `**/` automatically unless they start with `./`, assuming that's what the old CLI does, that hasn't been implemented yet. That said @Abreuvoir's config doesn't seem to be affected by that problem, so there might be another bug 🤔 I'll try to reproduce once I get back home.

**Comment by Mathias-S** [comment]
Sorry for going a bit off-topic, but I also had an issue with the `@ianvs/prettier-plugin-sort-imports` plugin's `importOrder` mentioned in @Abreuvoir's config, so there may be a compatibility issue between the new CLI and that plugin (it seemed like the `importOrder` property wasn't read correctly, or possibly at all, with the new CLI).

**Comment by fabiospampinato** [comment]
@Mathias-S Interestingly, thanks, I'll have a look 👍

**Comment by oprypkhantc** [comment]
@Mathias-S @fabiospampinato It doesn't seem related to `@ianvs/prettier-plugin-sort-imports` at all. For me, even with experimental CLI turned off, and with an option like `singleQuote: false` it still doesn't pick up on the overrides. Even a glob for all files still doesn't seem to match anything: `- files: '**/*'`

**Comment by tryone144** [comment]
> it seemed like the `importOrder` property wasn't read correctly, or possibly at all, with the new CLI

This should probably be its own issue. `overrides` currently only pass on normalized configuration directives, no plugin options: https://github.com/prettier/prettier-cli/blob/4b1a66a1b8d7091ba53a37b4762b7863eaf09585/src/utils.ts#L659-L660
This is in contrast to the top-level configuration object which keeps everything (therefore also unknown plugin options) and only normalizes known directives: https://github.com/prettier/prettier-cli/blob/4b1a66a1b8d7091ba53a37b4762b7863eaf09585/src/config_prettier.ts#L94 https://github.com/prettier/prettier-cli/blob/4b1a66a1b8d7091ba53a37b4762b7863eaf09585/src/utils.ts#L640-L643

**Comment by tryone144** [comment]
A shot in the dark, but could be Windows paths be the common denominator? In contrast to the cases where adding `**/` to the glob has fixed the issue.

**Comment by 43081j** [comment]
does one of you experiencing exactly @eamodio's problem have a repo where it can be reproduced?

**Comment by Abreuvoir** [comment]
3.6.1 did not change anything for me

**Comment by tordans** [comment]
Using Prettier 3.6.2 with the new cli flag I have to change my overwrites like this:
```diff
  overrides: [
    {
      files:
-        'src/app/regionen/[regionSlug]/_components/SidebarInspector/TagsTable/translations/*.const.ts',
+        '**/translations/*.const.ts',
      options: {
        printWidth: 1000,
      },
    },
  ],
```

**Comment by kirillgroshkov** [comment]
This overrides config works differently for me (versus the classic CLI):

```
overrides: [
    {
       files: ['**/tsconfig.json', '**/tsconfig.*.json'],
       options: {
        parser: 'jsonc',
      },
    },
  ],
```

The root tsconfig.json respects the `parser: jsonc`, but `scripts/tsconfig.json` file in my repo does **not** respect the overrides.

`files: ['tsconfig.json', 'tsconfig.*.json']`
doesn't work either

**Comment by tryone144** [comment]
@dubzzz is your specific issue that plugin options in `overrides` are not honoured?

Please check if https://github.com/prettier/prettier-cli/pull/73 fixes your issue.
